### ISSUE TITLE
OSGB36.toWGS84 uses the wrong ellipsoid

### ISSUE THREAD

**Issue by kylecorry31** [dstl/osgb#1]
I may be wrong here as coordinate math isn't my strength, but I believe the current implementation of OSGB36.toWGS84 is incorrect. In my testing converting to an OSNG string and back to a WGS84 coordinate did not present the same value as the original WGS84 coordinate. I believe the issue is that the to and from ellipsoids are swapped; on my fork of this repo, I made the following change and it resolved the problem for me: https://github.com/kylecorry31/osgb/commit/1df79ea6951294a5d8d4f2b09b6333cc3b62b253

**Comment by jbaker-dstl** [comment]
Thanks for flagging this, I believe you're correct and have fixed the problem.
